### ISSUE TITLE
I am getting this error while installation

### ISSUE THREAD

**Issue by arsalan993** [robjhyndman/anomalous-acm#13]
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  'curl' call had nonzero exit status
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘rgl’ failed
Installation failed: subscript out of bounds
'/home/test/anaconda3/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL '/tmp/RtmpNgn3Bc/devtools2f8643039054/ks'  \
  --library='/home/test/anaconda3/lib/R/library' --install-tests 

ERROR: dependency ‘rgl’ is not available for package ‘ks’
* removing ‘/home/test/anaconda3/lib/R/library/ks’
Installation failed: Command failed (1)
'/home/test/anaconda3/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpNgn3Bc/devtools2f86109209dc/hdrcde'  \
  --library='/home/test/anaconda3/lib/R/library' --install-tests 

ERROR: dependency ‘ks’ is not available for package ‘hdrcde’
* removing ‘/home/test/anaconda3/lib/R/library/hdrcde’
Installation failed: Command failed (1)
'/home/test/anaconda3/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpNgn3Bc/devtools2f867c367d45/robjhyndman-anomalous-acm-79d50aa'  \
  --library='/home/test/anaconda3/lib/R/library' --install-tests 

ERROR: dependencies ‘alphahull’, ‘hdrcde’ are not available for package ‘anomalousACM’
* removing ‘/home/test/anaconda3/lib/R/library/anomalousACM’
Installation failed: Command failed (1)
>                                       

similar error while installing cut down version
My OS is ubuntu 17.04

**Comment by robjhyndman** [comment]
Please read the error messages. The problem is not with the anomalous package, but with curl, and possibly rgl.
