### ISSUE TITLE
KLscore computation error for shorter time series

### ISSUE THREAD

**Issue by kasungayan** [robjhyndman/anomalous-acm#7]
Hi,

When using the anomalous package for shorter time series (i.e below than 2*frequency), the package gave me an error stating that it cannot compute the KL score "I cannot compute KLscore when the length is too small.". When I debugged the code, I found the relevant constraint in [1], which doesn't accommodate for shorter time series that violates the aforementioned condition. Although ideally, it should log a warning message and continue with the rest of the computation. But according to [2], it causes to stop the program abruptly, without logging the computed values of other features (i.e other than KL Score) 

Thanks ! 

[1] https://github.com/robjhyndman/anomalous/blob/master/R/tsmeasures.R#L204
[2] https://github.com/robjhyndman/anomalous/blob/master/R/tsmeasures.R#L205

**Comment by earowang** [comment]
Thanks for reporting this. It gives a warning when the time series is too short to compute KLscore rather than quitting the computation.
